### ISSUE TITLE
[Typo]: タイトルが 2022 のまま

### ISSUE THREAD

**Issue by TwoSquirrels** [uchikoshi-fes/uchikoshi-fes.jp-2023#1]
### URL

https://uchikoshi-fes.jp/

### 現在の状況

タイトルが `第44回打越祭公式サイト (浅野学園2022年度文化祭)` になってる。
今年度の文化祭は **2023** 年度なのでこれはウソ。

### あるべき姿

タイトルは `第44回打越祭公式サイト (浅野学園2023年度文化祭)` であるべき。

**Comment by gendaineko2222** [comment]
ありがとうございます！
