### ISSUE TITLE
[改善]: SNSへのリンクを別タブで開くように

### ISSUE THREAD

**Issue by ryo-ha-gi** [uchikoshi-fes/uchikoshi-fes.jp-2023#16]
### 改善対象の事柄

カイカ宣言の下にあるリンクを押すと打越祭のページが更新される

### 期待する挙動

打越祭のページに戻りやすいように、新しいタブで開くようにする

**Comment by TwoSquirrels** [comment]
これ、外部のタグ全部別タブで開くようにしたほうがいいと思うので、Link コンポーネントを作るなどして共通化させるとよさそう。
[昨年の Link コンポーネントはこんな感じ。](https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2022/blob/main/components/base/link.jsx)
