### ISSUE TITLE
[Bug]: 音声読み上げで適切に読み上げられない

### ISSUE THREAD

**Issue by chakkun1121** [uchikoshi-fes/uchikoshi-fes.jp-2023#47]
### URL

https://develop.uchikoshi-fes-2023.pages.dev/orgs/%E7%89%A9%E7%90%86%E9%83%A8%E5%B1%95%EF%BC%832023

### 現在の状況

カテゴリー:展示 のところが展示のところだけがリンクになっているので読み上げのときに分割されてしまい、関連性が分かりづらくなっている

### スクリーンショット

https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2023/assets/99847806/39aa053a-29be-470b-8126-e0dcc97838c8

![image](https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2023/assets/99847806/5aeb6e26-8afe-4f64-939c-fe25ccbafa1a)

### 期待する挙動

適切に繋いで読み上げられる

### OS

その他

### ブラウザ

Chrome

### 環境情報

chromeos Version 116.0.5845.168 (Official Build) (64-bit)

**Comment by chakkun1121** [comment]
他にもトップページの方でも同じようなことになっています。
↓適切に読み上げられないところ

![image](https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2023/assets/99847806/905b8893-bb4b-4aea-aea6-a0faeb744219)

![image](https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2023/assets/99847806/9b734237-e297-4382-bf43-4a31d844b04d)

**Comment by ryo-ha-gi** [comment]
日付とカイカ宣言が正しく読まれないことは確認しました。
他の部分は、ChromeVox の検索キーを使って移動する場合は問題なさそうでした。
