### ISSUE TITLE
[改善]: マップがロード中であることを示す

### ISSUE THREAD

**Issue by gendaineko2222** [uchikoshi-fes/uchikoshi-fes.jp-2023#7]
### 改善対象の事柄

マップがロードされていないとき何もないようにみえる

### 期待する挙動

何らかの方法でロード中であることを表す
薄い四角を後ろに置くなど

### 補足情報

![IMG_1154](https://github.com/uchikoshi-fes/uchikoshi-fes.jp-2023/assets/93499945/d3ea60e9-8920-4843-82c7-eac57a4b114b)

**Comment by ryo-ha-gi** [comment]
一応 map の背景色を変えたけど期待通りに表示されているかは不明です
